<a href="https://colab.research.google.com/github/imagimaniac/Practice_repo/blob/main/ProjectEuler.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Priblem 1**

**If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23. Find the sum of all the multiples of 3 or 5 below 1000**

In [ ]:
N = 20
sum = 0
for i in range(1000):
  if ((i%3 == 0) or (i%5 == 0)):
    sum += i
else:
  print(sum)

233168

**Priblem 2**

**Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:***

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

***By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.***

In [ ]:
n = 34  # for getting terms < 4,000,000 first 34 terms are sufficient
f1 = 0
f2 = 1
for x in range(1, n):
    next = f1 + f2
    f1 = f2
    f2 = next
    sumoffib = f1 +f2
      
print(printFibonacciNumbers(n))
print('sum of fib= ', sumoffib)

**using end='  '**

In [ ]:
n = int(input('No of terms in Fibonacci sequence: '))
def printFibonacciNumbers(n):
    f1 = 0
    f2 = 1
    if (n<1):
      return
    print(f1, end=' ')
    for x in range(1, n):
      print(f2, end=' ')
      next = f1 + f2
      f1 = f2
      f2 = next
print(printFibonacciNumbers(n))

No of terms in Fibonacci sequence: 34
0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584 4181 6765 10946 17711 28657 46368 75025 121393 196418 317811 514229 832040 1346269 2178309 3524578 None

**USing SET datatype** **all fib**

In [ ]:
n = 33  # for getting terms < 4,000,000 first 34 terms are sufficient
f1 = 0
f2 = 1
sumoffib = 0
setoffib = {f1, f2}
for x in range(1, n):
    next = f1 + f2
    f1 = f2
    f2 = next
    setoffib.add(f2)
    sumoffib = sumoffib +f2
print(sorted(setoffib))
print('sum of fib= ', sumoffib)

[0, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578]
sum of fib=  9227463

**Sum of even terms in fibonacci**

In [ ]:
n = 33            # for getting sum < 4,000,000 first 33 terms are sufficient
f1 = 0
f2 = 1
sumoffib = f1 + f2
setoffib = {f1, f2}
for x in range(1, n):
    next = f1 + f2
    f1 = f2
    f2 = next
    if f2%2 == 0:
      continue
    setoffib.add(f2)
    sumoffib = sumoffib +f2
print(sorted(setoffib))
print('sum of fib= ', sumoffib)

In [ ]:
#Using a recursive function

def fib(num):
      '''
      recursive function to calculate fibonacci serise 
      '''
      return num if num <= 1 else fib(num-1) + fib(num-2)

nterm = int(input("Enter the number of terms in fibonacci serise:  "))
for num in range(nterm):
      print(fib(num), end="   ")

Enter the number of terms in fibonacci serise:  10
0   1   1   2   3   5   8   13   21   34

In [ ]:
def get_even_fib_sum(N):
    fib_list = [0,1] 
    for i in range(N):
        fib_list.append(fib_list[i+1] + fib_list[i])
        #if fib_list[i+2] > 4000000:
        #fib_list.pop(i+2)
            #break

    return (fib_list)

all_fib_terms = get_even_fib_sum(33)
all_fib_terms

[0,
 1,
 1,
 2,
 3,
 5,
 8,
 13,
 21,
 34,
 55,
 89,
 144,
 233,
 377,
 610,
 987,
 1597,
 2584,
 4181,
 6765,
 10946,
 17711,
 28657,
 46368,
 75025,
 121393,
 196418,
 317811,
 514229,
 832040,
 1346269,
 2178309,
 3524578,
 5702887]

In [ ]:
b = sum(all_fib_terms)
print(b)

14930351

**Problem 3**

***Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.***

In [ ]:
sum_of_squares = 0
square_of_sum = 0
for i in range(1,101,1):     # 1 is inclusive and 11 is exclusive
    sum_of_squares += i**2
    square_of_sum += i
print(sum_of_squares)
print(square_of_sum**2)
print(square_of_sum**2 - sum_of_squares)

338350
25502500
25164150

***Now trying to use function for above problem for diff between sum of squares and square of sum of first N numbers***

In [ ]:
def diff_sumofsq_n_sqofsum(N):
    sum_of_squares = 0
    square_of_sum = 0
    for i in range(1,N+1):    
       sum_of_squares += i**2
       square_of_sum += i
    diff = square_of_sum**2 - sum_of_squares 
    return diff


print(diff_sumofsq_n_sqofsum(25))
print(diff_sumofsq_n_sqofsum(50))
print(diff_sumofsq_n_sqofsum(100))
diff_sumofsq_n_sqofsum(5)     #this get executed only but only latest value is printted
diff_sumofsq_n_sqofsum(10)

***Problem 4***


By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

What is the 10 001st prime number?

Even fibonacci serise using **filter**

In [ ]:
n = 20  # for getting terms < 4,000,000 first 34 terms are sufficient
f1 = 0
f2 = 1
sumoffib = 0
listoffib = [f1, f2]
for x in range(1, n):
    next = f1 + f2
    f1 = f2
    f2 = next
    listoffib.append(f2)
    sumoffib = sumoffib +f2
print(sorted(setoffib))
print('sum of fib= ', sumoffib)

[0, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765]
sum of fib=  17709

In [ ]:
help("math")

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.

    acosh(x, /)
        Return the inverse hyperbolic cosine of x.

    asin(x, /)
        Return the arc sine (measured in radians) of x.

    asinh(x, /)
        Return the inverse hyperbolic sine of x.

    atan(x, /)
        Return the arc tangent (measured in radians) of x.

    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.

        Unlike atan(y/x), the signs of both x and y are considered.

    atanh(x, /)
        Return the inverse hyperbolic tangent of x.

    ceil(x, /)
        Return the ceiling of x as an Integral.

        This is the smallest integer >= x.

    copysign(x, y, /)
        Return a float with the magnitude (absolute value) of x but the sign of y.

        On platforms that support signed zeros, copysign(1.0, -0.0)
        returns -1.0.

    cos(x, /)
        Return the cosine of x (measured in radians).

    cosh(x, /)
        Return the hyperbolic cosine of x.

    degrees(x, /)
        Convert angle x from radians to degrees.

    erf(x, /)
        Error function at x.

    erfc(x, /)
        Complementary error function at x.

    exp(x, /)
        Return e raised to the power of x.

    expm1(x, /)
        Return exp(x)-1.

        This function avoids the loss of precision involved in the direct evaluation of exp(x)-1 for small x.

    fabs(x, /)
        Return the absolute value of the float x.

    factorial(x, /)
        Find x!.

        Raise a ValueError if x is negative or non-integral.

    floor(x, /)
        Return the floor of x as an Integral.

        This is the largest integer <= x.

    fmod(x, y, /)
        Return fmod(x, y), according to platform C.

        x % y may differ.

    frexp(x, /)
        Return the mantissa and exponent of x, as pair (m, e).

        m is a float and e is an int, such that x = m * 2.**e.
        If x is 0, m and e are both 0.  Else 0.5 <= abs(m) < 1.0.

    fsum(seq, /)
        Return an accurate floating point sum of values in the iterable seq.

        Assumes IEEE-754 floating point arithmetic.

    gamma(x, /)
        Gamma function at x.

    gcd(x, y, /)
        greatest common divisor of x and y

    hypot(x, y, /)
        Return the Euclidean distance, sqrt(x*x + y*y).

    isclose(a, b, *, rel_tol=1e-09, abs_tol=0.0)
        Determine whether two floating point numbers are close in value.

          rel_tol
            maximum difference for being considered "close", relative to the
            magnitude of the input values
          abs_tol
            maximum difference for being considered "close", regardless of the
            magnitude of the input values

        Return True if a is close in value to b, and False otherwise.

        For the values to be considered close, the difference between them
        must be smaller than at least one of the tolerances.

        -inf, inf and NaN behave similarly to the IEEE 754 Standard.  That
        is, NaN is not close to anything, even itself.  inf and -inf are
        only close to themselves.

    isfinite(x, /)
        Return True if x is neither an infinity nor a NaN, and False otherwise.

    isinf(x, /)
        Return True if x is a positive or negative infinity, and False otherwise.

    isnan(x, /)
        Return True if x is a NaN (not a number), and False otherwise.

    ldexp(x, i, /)
        Return x * (2**i).

        This is essentially the inverse of frexp().

    lgamma(x, /)
        Natural logarithm of absolute value of Gamma function at x.

    log(...)
        log(x, [base=math.e])
        Return the logarithm of x to the given base.

        If the base not specified, returns the natural logarithm (base e) of x.

    log10(x, /)
        Return the base 10 logarithm of x.

    log1p(x, /)
        Return the natural logarithm of 1+x (base e).

        The result is computed in a way which is accurate for x near zero.

    log2(x, /)
        Return the base 2 logarithm of x.

    modf(x, /)
        Return the fractional and integer parts of x.

        Both results carry the sign of x and are floats.

    pow(x, y, /)
        Return x**y (x to the power of y).

    radians(x, /)
        Convert angle x from degrees to radians.

    remainder(x, y, /)
        Difference between x and the closest integer multiple of y.

        Return x - n*y where n*y is the closest integer multiple of y.
        In the case where x is exactly halfway between two multiples of
        y, the nearest even value of n is used. The result is always exact.

    sin(x, /)
        Return the sine of x (measured in radians).

    sinh(x, /)
        Return the hyperbolic sine of x.

    sqrt(x, /)
        Return the square root of x.

    tan(x, /)
        Return the tangent of x (measured in radians).

    tanh(x, /)
        Return the hyperbolic tangent of x.

    trunc(x, /)
        Truncates the Real x to the nearest Integral toward 0.

        Uses the __trunc__ magic method.

DATA
    e = 2.718281828459045
    inf = inf
    nan = nan
    pi = 3.141592653589793
    tau = 6.283185307179586

FILE
    (built-in)